SELECT A.PRODUCT_CODE,
       A.PRICE * B.AMOUNT AS 'SALES'
       
FROM PRODUCT AS A

JOIN (SELECT SUM(SALES_AMOUNT) AS AMOUNT,
             PRODUCT_ID
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID
     ) AS B
ON A.PRODUCT_ID = B.PRODUCT_ID

ORDER BY SALES DESC, PRODUCT_CODE ASC;